"""@generated by the upstream lowerquality/gentle project."""
import os

from setuptools import setup

from gentle import __version__


def list_relative_dir(relpath):
    here = os.path.dirname(os.path.realpath(__file__))
    startingdir = os.path.join(here, relpath)
    ans = []
    for root, _dirs, files in os.walk(startingdir):
        for ifile in files:
            fullpath = os.path.join(root, ifile)
            relativized = fullpath[len(here) + 1 :]
            ans.append(relativized)
    return ans


setup(
    app=["serve.py"],
    author="Robert M Ochshorn",
    description="Robust yet lenient forced-aligner built on Kaldi.",
    install_requires=["twisted"],
    license="MIT",
    name="gentle",
    options={"py2app": {"argv_emulation": False, "resources": "ffmpeg,www,exp"}},
    packages=["gentle", "gentle.util"],
    package_data={
        "gentle": ["ext/k3", "ext/m3"] + list_relative_dir("exp") + list_relative_dir("www")
    },
    test_suite="tests",
    url="http://lowerquality.com/gentle",
    version=__version__,
)
